### ISSUE TITLE
Enable custom test-suite commands

### ISSUE THREAD

**Issue by dobraczka** [dobraczka/recite#4]
At the moment the test-suite command is fixed to be `nox -r`, this should be customizable. Probably like this:

```toml
[tool.recite]
run_tests = ["tox", "run", "-e", "mytests"]
```

in the `pyproject.toml`.
